version: '3'
services:
    postgres:
        image: postgres
        container_name: postgres-task
        restart: always
        volumes:
            - ./pgdata:/var/lib/postgresql/data
            - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
        environment:
            - POSTGRES_PASSWORD=taskpassword
            - POSTGRES_USER=taskuser
            - POSTGRES_DB=task
        expose:
            - "5432"
        ports:
          - 5040:5432
        healthcheck:
            test: pg_isready -U taskuser -d task
            interval: 10s
            timeout: 3s
            retries: 5

    go:
        image: golang:1.17
        container_name: go-task
        environment:
            - DB_CONNECTION_STRING=host=postgres user=taskuser port=5432 password=taskpassword dbname=task search_path=dronetask sslmode=disable
            - AUTH_SECRET_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
        volumes:
            - .:/usr/src/myapp
        ports:
          - 8050:9090
        working_dir: /usr/src/myapp
        command: bash -c "env && go get -d && go get github.com/CloudInn/gorm-goose/cmd/gorm-goose && gorm-goose -path=repository/db -pgschema=dronetask up && go run *.go"

    swagger:
        image: quay.io/goswagger/swagger
        container_name: docs
        volumes:
            - .:/usr/src/app
        expose:
            - "4141"
        ports:
          - 4141:4141
        working_dir: /usr/src/app
        command: serve swagger.yml --no-open --port=4141