swagger: "2.0"
info:
  description: "This is a sample server swagger."
  version: "1.0.0"
  title: "Swagger Drone"
  contact:
    email: "yahya.qandel@gmail.com"
host: "localhost"
basePath: "/v2"
tags:
- name: "drone"
  description: "drones world"
- name: "medication"
  description: "medications"
schemes:
- "http"
paths:
  /drone:
    post:
      tags:
      - "drone"
      summary: "register new drone"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "drone object that needs to be registered"
        required: true
        schema:
          $ref: "#/definitions/Drone"
      responses:
        "400":
          description: "Invalid input"
        "401":
          description: "un authorized"
      security:
      - Bearer: []
  /drone/load:
    post:
      tags:
      - "drone"
      summary: "load drone by medication"
      produces:
      - "application/json"
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "drone load by medication"
        required: true
        schema:
          $ref: "#/definitions/DroneLoad"
      responses:
        "200":
          description: "drone {drone name} loaded with medication {medicaiton name}"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Drone"
        "400":
          description: "Invalid input"
        "401":
          description: "un authorized"
      security:
      - Bearer: []
  /drone/medication:
    get:
      tags:
      - "drone"
      summary: "Find all loaded mediactions for specific drone"
      produces:
      - "application/json"
      parameters:
      - name: "drone_serial_number"
        in: "query"
        description: "medications loaded by single drone"
        required: true
        type: "string"
      responses:
        "200":
          description: "list od all medications objects"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Medication"
        "400":
          description: "Invalid input"
        "401":
          description: "un authorized"
      security:
      - Bearer: []
  /drone/available:
    get:
      tags:
      - "drone"
      summary: "list all avaialble drones"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Drone"
            type: "array"
        "400":
          description: "Invalid operation"
        "401":
          description: "un authorized"
      security:
      - Bearer: []
  /drone/battery:
    get:
      tags:
      - "drone"
      summary: "get drone battery percentage"
      consumes:
      - "query param"
      produces:
      - "application/json"
      parameters:
      - name: "drone_serial_number"
        in: "query"
        description: "serial number of drone"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/DroneBattery"
        "401":
          description: "un authorized"
      security:
      - Bearer: []
  /medication:
    post:
      tags:
      - "medication"
      summary: "register mediacation"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "image"
        in: "formData"
        description: "image to upload"
        required: true
        type: "file"
      - name: "name"
        in: "formData"
        description: "medication name"
        required: true
        type: "string"
        format: "allowed only letters, numbers, ‘-‘, ‘_’"
      - name: "code"
        in: "formData"
        description: "medication code"
        required: true
        type: "string"
        format: "allowed only upper case letters, underscore and numbers"
      - name: "weight"
        in: "formData"
        description: "medication weight in float"
        required: true
        type: "number"
      responses:
        "201":
          description: "successful operation"
          schema:
            type: "object"
            $ref: "#/definitions/Medication"
      security:
      - api_key: []

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  DroneBattery:
    type: "object"
    properties:
      battery_level:
        type: "number"
  Medication:
    type: "object"
    required:
    - "name"
    - "code"
    - "photo"
    - "weight"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
        format: "allowed only letters, numbers, ‘-‘, ‘_’"
      code:
        type: "string"
        format: "allowed only upper case letters, underscore and numbers"
      photo:
        type: "string"
        description: "url for medication image"
      weight:
        type: "number"
  DroneLoad:
    type: "object"
    required:
    - "drone_serial_number"
    properties:
      drone_serial_number:
        type: "string"
      medication_code:
        type: string
  Drone:
    type: "object"
    required:
    - "name"
    - "model"
    - "weight"
    properties:
      name:
        type: "string"
        example: "antibioticsDrone"
        format: "100 characters max"
      model:
        type: "string"
        enum:
        - Lightweight
        - Middleweight 
        - Cruiserweight
        - Heavyweight
      weight:
        type: "number"
        format: "float64"
      state:
        type: "string"
        description: "drone state"
        enum:
        - IDLE
        - LOADED
        - LOADING
        - DELIVERING
        - DELIVERED
        - RETURNING
        default: "IDLE"