version: '3'
services:
    postgres:
        image: postgres
        container_name: postgres-task-test
        restart: always
        volumes:
            - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
        environment:
            - POSTGRES_PASSWORD=taskpassword
            - POSTGRES_USER=taskuser
            - POSTGRES_DB=tasktest
        expose:
            - "5432"
        # for debugging
        ports:
          - 5050:5432
        healthcheck:
            test: pg_isready -U taskuser -d tasktest
            interval: 10s
            timeout: 3s
            retries: 5

    go:
        image: golang:1.17
        container_name: go-task-test
        environment:
            - TEST_DB_CONNECTION_STRING=host=postgres user=taskuser port=5432 password=taskpassword dbname=tasktest search_path=dronetask sslmode=disable
        volumes:
            - ../:/usr/src/myapp
        working_dir: /usr/src/myapp
        command: bash -c "env && go get -d && go get github.com/CloudInn/gorm-goose/cmd/gorm-goose && gorm-goose -env test -path=repository/db -pgschema=dronetask up && go test --cover -v ./..."